// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Stride.TTF;
#pragma warning restore 0105

namespace Stride.TTF
{
    public static partial class TTFInterop
    {
        public const string NativeLib = "ttf2meshbind.dll";

        static TTFInterop()
        {
        }


        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "my_function")]
        public static extern void my_function(Vector2 input);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "char_mesh_2d")]
        public static extern BufferVec2 char_mesh_2d(ref byte file_buf, uint length, uint ch, byte quality);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "display_numbers")]
        public static extern void display_numbers(ref byte buffer, uint length);

    }

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct BufferVec2
    {
        public IntPtr data;
        public uint len;
    }

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct Vector2
    {
        public float x;
        public float y;
    }



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error): base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
